/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as ExamResultRouteImport } from './routes/exam.result'
import { Route as ExamRecordRouteImport } from './routes/exam.record'
import { Route as ExamStepStepRouteImport } from './routes/exam.step.$step'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamRoute,
} as any)
const ExamResultRoute = ExamResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ExamRoute,
} as any)
const ExamRecordRoute = ExamRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => ExamRoute,
} as any)
const ExamStepStepRoute = ExamStepStepRouteImport.update({
  id: '/step/$step',
  path: '/step/$step',
  getParentRoute: () => ExamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centers': typeof CentersRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/exam/record': typeof ExamRecordRoute
  '/exam/result': typeof ExamResultRoute
  '/exam/': typeof ExamIndexRoute
  '/exam/step/$step': typeof ExamStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centers': typeof CentersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/exam/record': typeof ExamRecordRoute
  '/exam/result': typeof ExamResultRoute
  '/exam': typeof ExamIndexRoute
  '/exam/step/$step': typeof ExamStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centers': typeof CentersRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/exam/record': typeof ExamRecordRoute
  '/exam/result': typeof ExamResultRoute
  '/exam/': typeof ExamIndexRoute
  '/exam/step/$step': typeof ExamStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centers'
    | '/dashboard'
    | '/exam'
    | '/login'
    | '/report'
    | '/signup'
    | '/exam/record'
    | '/exam/result'
    | '/exam/'
    | '/exam/step/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centers'
    | '/dashboard'
    | '/login'
    | '/report'
    | '/signup'
    | '/exam/record'
    | '/exam/result'
    | '/exam'
    | '/exam/step/$step'
  id:
    | '__root__'
    | '/'
    | '/centers'
    | '/dashboard'
    | '/exam'
    | '/login'
    | '/report'
    | '/signup'
    | '/exam/record'
    | '/exam/result'
    | '/exam/'
    | '/exam/step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentersRoute: typeof CentersRoute
  DashboardRoute: typeof DashboardRoute
  ExamRoute: typeof ExamRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/result': {
      id: '/exam/result'
      path: '/result'
      fullPath: '/exam/result'
      preLoaderRoute: typeof ExamResultRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/record': {
      id: '/exam/record'
      path: '/record'
      fullPath: '/exam/record'
      preLoaderRoute: typeof ExamRecordRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/step/$step': {
      id: '/exam/step/$step'
      path: '/step/$step'
      fullPath: '/exam/step/$step'
      preLoaderRoute: typeof ExamStepStepRouteImport
      parentRoute: typeof ExamRoute
    }
  }
}

interface ExamRouteChildren {
  ExamRecordRoute: typeof ExamRecordRoute
  ExamResultRoute: typeof ExamResultRoute
  ExamIndexRoute: typeof ExamIndexRoute
  ExamStepStepRoute: typeof ExamStepStepRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamRecordRoute: ExamRecordRoute,
  ExamResultRoute: ExamResultRoute,
  ExamIndexRoute: ExamIndexRoute,
  ExamStepStepRoute: ExamStepStepRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentersRoute: CentersRoute,
  DashboardRoute: DashboardRoute,
  ExamRoute: ExamRouteWithChildren,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
